Repository thatlonelybugbear/automated-conditions-5e, pull requests merged in 2025-08, with the labels that each got.

#480 game.i18n.translations.DND5E?.[string] ?? game.i18n.localize(string);
  scripts/ac5e-helpers.mjs
Labels: bug

#482 Thatlonelybugbear patch 2
  Changelog.md
Labels: enhancement

#485 Update pt-BR.json
  lang/pt-BR.json
Labels: i18n

#491 Hexagonal grid distance
  scripts/ac5e-helpers.mjs
Labels: bug, enhancement

#519 461 enhancement when ammo is used add ammunitions properties in the items rolldata
  Changelog.md
  scripts/ac5e-helpers.mjs
Labels: enhancement

#521 5.1.x compatibility
  Changelog.md
  module.json
  scripts/ac5e-helpers.mjs
  scripts/ac5e-hooks.mjs
  scripts/ac5e-setpieces.mjs
Labels: enhancement

#526 Update pt-BR.json
  lang/pt-BR.json
Labels: i18n

#532 Added `_getTooltip` call in `_preConfigureInitiative`
  scripts/ac5e-hooks.mjs
Labels: bug

#535 Update it.json
  lang/it.json
Labels: i18n
