Repository thatlonelybugbear/automated-conditions-5e, pull requests merged in 2025-05, with the labels that each got.

#306 Fix for wrong localization string in settings
  scripts/ac5e-settings.mjs
Labels: bug

#316 Fix for subjectTokenId undefined when no message is created
  scripts/ac5e-hooks.mjs
Labels: bug

#317 Update pt-BR.json
  lang/pt-BR.json
Labels: enhancement

#333 Fix _canSee()
  scripts/ac5e-helpers.mjs
Labels: bug

#337 Update pt-BR.json
  lang/pt-BR.json
Labels: i18n

#338 Can See again
  scripts/ac5e-helpers.mjs
Labels: bug

#341 Reinstate `targetActor` in sandbox evaluations
  scripts/ac5e-helpers.mjs
Labels: bug

#343 Autoranged always returning short due to botched midicheckrange test
  scripts/ac5e-helpers.mjs
Labels: bug

#353 Remove `dialog.configure` manipulation for now
  scripts/ac5e-hooks.mjs
Labels: bug

#359 [#357] Limit uses of AC5e flags on owned actors by a specific Number
  scripts/ac5e-setpieces.mjs
Labels: enhancement

#371 Added spell sniper flag in DAE autocompletion
  lang/en.json
Labels: i18n
