Repository thatlonelybugbear/automated-conditions-5e, pull requests merged in 2025-10, with the labels that each got.

#557 Unintended removal of `!` from conditions
  scripts/ac5e-setpieces.mjs
Labels: bug

#567 Reinstate `itemProperties`
  scripts/ac5e-helpers.mjs
Labels: bug

#572 Update pt-BR.json
  lang/pt-BR.json
Labels: i18n

#577 Rework bonus and set hints
  lang/en.json
Labels: enhancement, i18n

#580 Update it.json
  lang/it.json
Labels: i18n
