Repository thatlonelybugbear/automated-conditions-5e, pull requests merged in 2025-07, with the labels that each got.

#428 More sandbox fixes
  scripts/ac5e-helpers.mjs
Labels: enhancement

#448 Update it.json
  lang/it.json
Labels: i18n

#449 Update pl.json
  lang/pl.json
Labels: i18n

#465 fix heal activities not having healing.parts
  scripts/ac5e-helpers.mjs
Labels: bug

#468 463 bug button colorpicker misbehaving
  Changelog.md
  scripts/ac5e-helpers.mjs
  scripts/ac5e-hooks.mjs
Labels: bug

#454 Update pl.json
  lang/pl.json
Labels: i18n

#472 Update it.json
  lang/it.json
Labels: i18n
